export const APPLICATION_OPERATIONS = [
  'repository.list',
  'repository.connect',
  'repository.read',
  'repository.manage',
  'branch.read',
  'branch.create',
  'configuration.read',
  'configuration.update',
  'collection.read',
  'entry.read',
  'entry.create',
  'entry.update',
  'entry.rename',
  'entry.delete',
  'entry.history',
  'media.read',
  'media.write',
  'media.delete',
  'reference.read',
  'action.read',
  'action.run',
  'collaborator.read',
  'collaborator.invite',
  'collaborator.remove',
  'cache.read',
  'cache.invalidate',
  'account.read',
  'account.update',
  'admin.access',
] as const

export type ApplicationOperation = (typeof APPLICATION_OPERATIONS)[number]
