/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 2f07822ebad33c2c42607e1de32becbc)
interface __BaseEnv_Env {
	ADMIN_EMAILS: string;
	BASE_URL: string;
	CRYPTO_KEY: string;
	GITHUB_APP_ID: string;
	GITHUB_APP_NAME: string;
	GITHUB_APP_PRIVATE_KEY: string;
	GITHUB_APP_WEBHOOK_SECRET: string;
	GITHUB_APP_CLIENT_ID: string;
	GITHUB_APP_CLIENT_SECRET: string;
	RESEND_API_KEY: string;
	RESEND_FROM_EMAIL: string;
	DATABASE_URL: string;
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	DEPLOYMENT_MODE: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ADMIN_EMAILS" | "BASE_URL" | "CRYPTO_KEY" | "GITHUB_APP_ID" | "GITHUB_APP_NAME" | "GITHUB_APP_PRIVATE_KEY" | "GITHUB_APP_WEBHOOK_SECRET" | "GITHUB_APP_CLIENT_ID" | "GITHUB_APP_CLIENT_SECRET" | "RESEND_API_KEY" | "RESEND_FROM_EMAIL" | "DATABASE_URL" | "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL" | "DEPLOYMENT_MODE">> {}
}
